name: Pushes the bot locally
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.dockerignore'
      - '.gitignore'
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkouts the repository
        uses: actions/checkout@v2

      - name: Sets up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: SSH to Server and update bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/yiffposter
            chmod +x ./update
            ./update
